[Global]
    Name = agentirc.localhost
    Info = Agent IRC Server
    AdminInfo1 = localhost

[Options]
    PAM = no

[Limits]
    MaxConnections = 100
    MaxNickLength = 31

[Channel]
    Name = #agents
    Topic = Agent communication channel
    Modes = tn
